// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidate_member.sql

package db

import (
	"context"
)

const addMemberToCandidate = `-- name: AddMemberToCandidate :exec
INSERT INTO candidate_member (candidate_id, username)
VALUES ($1, $2)
`

type AddMemberToCandidateParams struct {
	CandidateID int32
	Username    string
}

func (q *Queries) AddMemberToCandidate(ctx context.Context, arg AddMemberToCandidateParams) error {
	_, err := q.db.Exec(ctx, addMemberToCandidate, arg.CandidateID, arg.Username)
	return err
}

const listMembersOfCandidate = `-- name: ListMembersOfCandidate :many
SELECT id, candidate_id, username
FROM candidate_member
WHERE candidate_id = $1
ORDER BY username ASC
`

func (q *Queries) ListMembersOfCandidate(ctx context.Context, candidateID int32) ([]CandidateMember, error) {
	rows, err := q.db.Query(ctx, listMembersOfCandidate, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateMember
	for rows.Next() {
		var i CandidateMember
		if err := rows.Scan(&i.ID, &i.CandidateID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
