// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidate.sql

package db

import (
	"context"
)

const createCandidate = `-- name: CreateCandidate :one
INSERT INTO candidate (period_id, position_id)
VALUES ($1, $2)
RETURNING id, period_id, position_id, created_at
`

type CreateCandidateParams struct {
	PeriodID   int32
	PositionID int32
}

func (q *Queries) CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error) {
	row := q.db.QueryRow(ctx, createCandidate, arg.PeriodID, arg.PositionID)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.PositionID,
		&i.CreatedAt,
	)
	return i, err
}

const getCandidate = `-- name: GetCandidate :one
SELECT id, period_id, position_id, created_at
FROM candidate
WHERE id = $1
`

func (q *Queries) GetCandidate(ctx context.Context, id int32) (Candidate, error) {
	row := q.db.QueryRow(ctx, getCandidate, id)
	var i Candidate
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.PositionID,
		&i.CreatedAt,
	)
	return i, err
}

const listCandidatesForPeriod = `-- name: ListCandidatesForPeriod :many
SELECT id, period_id, position_id, created_at
FROM candidate
WHERE period_id = $1
ORDER BY position_id ASC
`

func (q *Queries) ListCandidatesForPeriod(ctx context.Context, periodID int32) ([]Candidate, error) {
	rows, err := q.db.Query(ctx, listCandidatesForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Candidate
	for rows.Next() {
		var i Candidate
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.PositionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCandidatesWithMembers = `-- name: ListCandidatesWithMembers :many
SELECT c.id AS candidate_id, c.period_id, c.position_id, array_agg(cm.username) AS members
FROM candidate c
LEFT JOIN candidate_member cm ON c.id = cm.candidate_id
WHERE c.period_id = $1
GROUP BY c.id, c.period_id, c.position_id
ORDER BY c.position_id ASC
`

type ListCandidatesWithMembersRow struct {
	CandidateID int32
	PeriodID    int32
	PositionID  int32
	Members     interface{}
}

func (q *Queries) ListCandidatesWithMembers(ctx context.Context, periodID int32) ([]ListCandidatesWithMembersRow, error) {
	rows, err := q.db.Query(ctx, listCandidatesWithMembers, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCandidatesWithMembersRow
	for rows.Next() {
		var i ListCandidatesWithMembersRow
		if err := rows.Scan(
			&i.CandidateID,
			&i.PeriodID,
			&i.PositionID,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
