// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidate_decision.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCandidateDecision = `-- name: CreateCandidateDecision :one
INSERT INTO candidate_decision (candidate_id, username, status, response_deadline)
VALUES ($1, $2, $3, $4)
RETURNING id, candidate_id, username, status, notified_at, responded_at, response_deadline
`

type CreateCandidateDecisionParams struct {
	CandidateID      int32
	Username         string
	Status           DecisionStatus
	ResponseDeadline pgtype.Timestamptz
}

func (q *Queries) CreateCandidateDecision(ctx context.Context, arg CreateCandidateDecisionParams) (CandidateDecision, error) {
	row := q.db.QueryRow(ctx, createCandidateDecision,
		arg.CandidateID,
		arg.Username,
		arg.Status,
		arg.ResponseDeadline,
	)
	var i CandidateDecision
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.Username,
		&i.Status,
		&i.NotifiedAt,
		&i.RespondedAt,
		&i.ResponseDeadline,
	)
	return i, err
}

const declineExpiredDecision = `-- name: DeclineExpiredDecision :exec
UPDATE candidate_decision
SET status = 'declined', responded_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DeclineExpiredDecision(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, declineExpiredDecision, id)
	return err
}

const getCandidateDecision = `-- name: GetCandidateDecision :one
SELECT id, candidate_id, username, status, notified_at, responded_at, response_deadline
FROM candidate_decision
WHERE candidate_id = $1 AND username = $2
`

type GetCandidateDecisionParams struct {
	CandidateID int32
	Username    string
}

func (q *Queries) GetCandidateDecision(ctx context.Context, arg GetCandidateDecisionParams) (CandidateDecision, error) {
	row := q.db.QueryRow(ctx, getCandidateDecision, arg.CandidateID, arg.Username)
	var i CandidateDecision
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.Username,
		&i.Status,
		&i.NotifiedAt,
		&i.RespondedAt,
		&i.ResponseDeadline,
	)
	return i, err
}

const listPendingDecisionsPastDeadline = `-- name: ListPendingDecisionsPastDeadline :many
SELECT id, candidate_id, username, status, notified_at, responded_at, response_deadline FROM candidate_decision
WHERE status = 'pending' AND response_deadline < now()
`

func (q *Queries) ListPendingDecisionsPastDeadline(ctx context.Context) ([]CandidateDecision, error) {
	rows, err := q.db.Query(ctx, listPendingDecisionsPastDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidateDecision
	for rows.Next() {
		var i CandidateDecision
		if err := rows.Scan(
			&i.ID,
			&i.CandidateID,
			&i.Username,
			&i.Status,
			&i.NotifiedAt,
			&i.RespondedAt,
			&i.ResponseDeadline,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotified = `-- name: MarkNotified :one
UPDATE candidate_decision
SET notified_at = CURRENT_TIMESTAMP
WHERE candidate_id = $1 AND username = $2
RETURNING id, candidate_id, username, status, notified_at, responded_at, response_deadline
`

type MarkNotifiedParams struct {
	CandidateID int32
	Username    string
}

func (q *Queries) MarkNotified(ctx context.Context, arg MarkNotifiedParams) (CandidateDecision, error) {
	row := q.db.QueryRow(ctx, markNotified, arg.CandidateID, arg.Username)
	var i CandidateDecision
	err := row.Scan(
		&i.ID,
		&i.CandidateID,
		&i.Username,
		&i.Status,
		&i.NotifiedAt,
		&i.RespondedAt,
		&i.ResponseDeadline,
	)
	return i, err
}
