// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DecisionStatus string

const (
	DecisionStatusPending  DecisionStatus = "pending"
	DecisionStatusAccepted DecisionStatus = "accepted"
	DecisionStatusDeclined DecisionStatus = "declined"
)

func (e *DecisionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DecisionStatus(s)
	case string:
		*e = DecisionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DecisionStatus: %T", src)
	}
	return nil
}

type NullDecisionStatus struct {
	DecisionStatus DecisionStatus
	Valid          bool // Valid is true if DecisionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDecisionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DecisionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DecisionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDecisionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DecisionStatus), nil
}

type Candidate struct {
	ID         int32
	PeriodID   int32
	PositionID int32
	CreatedAt  pgtype.Timestamptz
}

type CandidateDecision struct {
	ID               int32
	CandidateID      int32
	Username         string
	Status           DecisionStatus
	NotifiedAt       pgtype.Timestamptz
	RespondedAt      pgtype.Timestamptz
	ResponseDeadline pgtype.Timestamptz
}

type CandidateMember struct {
	ID          int32
	CandidateID int32
	Username    string
}

type NominatedUser struct {
	ID           int32
	Username     string
	NominationID int32
}

type Nomination struct {
	ID          int32
	PositionID  int32
	PeriodID    int32
	SubmittedAt pgtype.Timestamptz
}

type NominationPeriod struct {
	ID             int32
	PositionID     int32
	OpensAt        pgtype.Timestamptz
	ClosesAt       pgtype.Timestamptz
	ConsolidatedAt pgtype.Timestamptz
}

type Position struct {
	ID           int32
	PositionName string
}
