// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nomination.sql

package db

import (
	"context"
)

const createNomination = `-- name: CreateNomination :one
INSERT INTO nomination (period_id, position_id)
VALUES ($1, $2)
RETURNING id, position_id, period_id, submitted_at
`

type CreateNominationParams struct {
	PeriodID   int32
	PositionID int32
}

func (q *Queries) CreateNomination(ctx context.Context, arg CreateNominationParams) (Nomination, error) {
	row := q.db.QueryRow(ctx, createNomination, arg.PeriodID, arg.PositionID)
	var i Nomination
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.PeriodID,
		&i.SubmittedAt,
	)
	return i, err
}

const getNominatedUsersForPeriod = `-- name: GetNominatedUsersForPeriod :many
SELECT n.id AS nomination_id, n.position_id, nu.username
FROM nomination n
JOIN nominated_user nu ON nu.nomination_id = n.id
WHERE n.period_id = $1
ORDER BY n.id
`

type GetNominatedUsersForPeriodRow struct {
	NominationID int32
	PositionID   int32
	Username     string
}

func (q *Queries) GetNominatedUsersForPeriod(ctx context.Context, periodID int32) ([]GetNominatedUsersForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getNominatedUsersForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNominatedUsersForPeriodRow
	for rows.Next() {
		var i GetNominatedUsersForPeriodRow
		if err := rows.Scan(&i.NominationID, &i.PositionID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNominationsForPeriod = `-- name: GetNominationsForPeriod :many
SELECT id, position_id, period_id, submitted_at
FROM nomination
WHERE period_id = $1
ORDER BY position_id ASC
`

func (q *Queries) GetNominationsForPeriod(ctx context.Context, periodID int32) ([]Nomination, error) {
	rows, err := q.db.Query(ctx, getNominationsForPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nomination
	for rows.Next() {
		var i Nomination
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.PeriodID,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
