// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nomination_period.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNominationPeriod = `-- name: CreateNominationPeriod :one
INSERT INTO nomination_period (position_id, opens_at, closes_at)
VALUES ($1, $2, $3)
RETURNING id, position_id, opens_at, closes_at
`

type CreateNominationPeriodParams struct {
	PositionID int32
	OpensAt    pgtype.Timestamptz
	ClosesAt   pgtype.Timestamptz
}

type CreateNominationPeriodRow struct {
	ID         int32
	PositionID int32
	OpensAt    pgtype.Timestamptz
	ClosesAt   pgtype.Timestamptz
}

func (q *Queries) CreateNominationPeriod(ctx context.Context, arg CreateNominationPeriodParams) (CreateNominationPeriodRow, error) {
	row := q.db.QueryRow(ctx, createNominationPeriod, arg.PositionID, arg.OpensAt, arg.ClosesAt)
	var i CreateNominationPeriodRow
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.OpensAt,
		&i.ClosesAt,
	)
	return i, err
}

const getNominationPeriod = `-- name: GetNominationPeriod :one
SELECT id, position_id, opens_at, closes_at, consolidated_at
FROM nomination_period
WHERE id = $1
`

func (q *Queries) GetNominationPeriod(ctx context.Context, id int32) (NominationPeriod, error) {
	row := q.db.QueryRow(ctx, getNominationPeriod, id)
	var i NominationPeriod
	err := row.Scan(
		&i.ID,
		&i.PositionID,
		&i.OpensAt,
		&i.ClosesAt,
		&i.ConsolidatedAt,
	)
	return i, err
}

const listAllNominationPeriods = `-- name: ListAllNominationPeriods :many
SELECT id, position_id, opens_at, closes_at, consolidated_at
FROM nomination_period
ORDER BY opens_at ASC
`

func (q *Queries) ListAllNominationPeriods(ctx context.Context) ([]NominationPeriod, error) {
	rows, err := q.db.Query(ctx, listAllNominationPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NominationPeriod
	for rows.Next() {
		var i NominationPeriod
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ConsolidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenNominationPeriods = `-- name: ListOpenNominationPeriods :many
SELECT id, position_id, opens_at, closes_at, consolidated_at
FROM nomination_period
WHERE consolidated_at IS NULL
ORDER BY opens_at ASC
`

func (q *Queries) ListOpenNominationPeriods(ctx context.Context) ([]NominationPeriod, error) {
	rows, err := q.db.Query(ctx, listOpenNominationPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NominationPeriod
	for rows.Next() {
		var i NominationPeriod
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ConsolidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodsPendingConsolidation = `-- name: ListPeriodsPendingConsolidation :many
SELECT id, position_id, opens_at, closes_at, consolidated_at
FROM nomination_period
WHERE consolidated_at IS NULL
ORDER BY opens_at ASC
`

func (q *Queries) ListPeriodsPendingConsolidation(ctx context.Context) ([]NominationPeriod, error) {
	rows, err := q.db.Query(ctx, listPeriodsPendingConsolidation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NominationPeriod
	for rows.Next() {
		var i NominationPeriod
		if err := rows.Scan(
			&i.ID,
			&i.PositionID,
			&i.OpensAt,
			&i.ClosesAt,
			&i.ConsolidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPeriodConsolidated = `-- name: SetPeriodConsolidated :exec
UPDATE nomination_period
SET consolidated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SetPeriodConsolidated(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, setPeriodConsolidated, id)
	return err
}
