// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: position.sql

package db

import (
	"context"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO position (position_name)
VALUES ($1)
RETURNING id, position_name
`

func (q *Queries) CreatePosition(ctx context.Context, positionName string) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition, positionName)
	var i Position
	err := row.Scan(&i.ID, &i.PositionName)
	return i, err
}

const deletePosition = `-- name: DeletePosition :one
DELETE FROM position
WHERE id = $1
RETURNING id, position_name
`

func (q *Queries) DeletePosition(ctx context.Context, id int32) (Position, error) {
	row := q.db.QueryRow(ctx, deletePosition, id)
	var i Position
	err := row.Scan(&i.ID, &i.PositionName)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT position_name
FROM position
WHERE id = $1
`

func (q *Queries) GetPosition(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var position_name string
	err := row.Scan(&position_name)
	return position_name, err
}

const listPositions = `-- name: ListPositions :many
SELECT position_name 
FROM position
ORDER BY id ASC
`

func (q *Queries) ListPositions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var position_name string
		if err := rows.Scan(&position_name); err != nil {
			return nil, err
		}
		items = append(items, position_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE position
SET position_name = $2
WHERE id = $1
RETURNING id, position_name
`

type UpdatePositionParams struct {
	ID           int32
	PositionName string
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.ID, arg.PositionName)
	var i Position
	err := row.Scan(&i.ID, &i.PositionName)
	return i, err
}
